# Generated by Django 2.1 on 2018-04-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jog',
            name='time',
            field=models.DurationField(),
        ),
    ]
